name: Docs
on:
  workflow_dispatch:
    inputs:
        use_password:
            description: 'Password protected?'
            type: boolean
            required: true
            default: true
  push:
    branches:
      - master
    paths:
      - docs/**

permissions:
  actions: write
  contents: write
  pages: write

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  GITHUB_ACTIONS: true

jobs:
  build_docs:
    runs-on: ubuntu-latest
    concurrency:
      group: docs_${{ github.head_ref || github.ref_name }}
      cancel-in-progress: true
    steps:
      - name: Set environment variables
        run: |
          echo "Use Pasword Input: ${{ github.event.inputs.use_password }}"
          echo "USE_PASSWORD=${{ github.event.inputs.use_password || 'true' }}" >> $GITHUB_ENV

      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"

      - name: Build Docs
        if: env.USE_PASSWORD == 'true'
        working-directory: docs/
        run: ./ci.sh
        env:
          STATICRYPT_PASSWORD: ${{ secrets.SITE_PASSWORD }}
          STATICRYPT_SALT: ${{ secrets.SITE_SALT }}
          STATICRYPT_REMEMBER: ${{ secrets.SITE_REMEMBER_DAYS }}

      - name: Build Docs (Public)
        if: env.USE_PASSWORD == 'false'
        working-directory: docs/
        run: |
          dotnet tool install -g docfx
          docfx

      - name: Publish Docs
        if: github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_site
          publish_branch: site
          force_orphan: true
